import type { Metadata } from "next";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";

export const nunito = Nunito_Sans({
	weight: ["400", "700"],
	style: ["normal", "italic"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "LokaTalent Admin",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${nunito.className} antialiased`}>
				{children}
			</body>
		</html>
	);
}
